import Sidebar from '@/components/sidebar';
import '../styles/global.scss';
import { Roboto } from 'next/font/google';
import './_layout.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Sidebar />
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
